# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1020, 600)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.widget.setObjectName("widget")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(584, 10, 331, 53))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_contact_status = QtWidgets.QLabel(self.widget)
        self.label_contact_status.setGeometry(QtCore.QRect(920, 179, 95, 103))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_contact_status.setFont(font)
        self.label_contact_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_contact_status.setScaledContents(False)
        self.label_contact_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_contact_status.setObjectName("label_contact_status")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(580, 180, 166, 102))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setText("")
        self.label_18.setScaledContents(False)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(940, 415, 59, 16))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(920, 10, 95, 53))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_date = QtWidgets.QLabel(self.widget)
        self.label_date.setGeometry(QtCore.QRect(30, 150, 231, 20))
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.label_conn_key = QtWidgets.QLabel(self.widget)
        self.label_conn_key.setGeometry(QtCore.QRect(306, 290, 269, 112))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_conn_key.setFont(font)
        self.label_conn_key.setFrameShape(QtWidgets.QFrame.Box)
        self.label_conn_key.setScaledContents(False)
        self.label_conn_key.setAlignment(QtCore.Qt.AlignCenter)
        self.label_conn_key.setObjectName("label_conn_key")
        self.label_function = QtWidgets.QLabel(self.widget)
        self.label_function.setGeometry(QtCore.QRect(30, 230, 231, 20))
        self.label_function.setAlignment(QtCore.Qt.AlignCenter)
        self.label_function.setObjectName("label_function")
        self.label_part = QtWidgets.QLabel(self.widget)
        self.label_part.setGeometry(QtCore.QRect(30, 70, 231, 20))
        self.label_part.setAlignment(QtCore.Qt.AlignCenter)
        self.label_part.setObjectName("label_part")
        self.label_time = QtWidgets.QLabel(self.widget)
        self.label_time.setGeometry(QtCore.QRect(30, 190, 231, 20))
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_fail_count = QtWidgets.QLabel(self.widget)
        self.label_fail_count.setGeometry(QtCore.QRect(490, 415, 59, 16))
        self.label_fail_count.setScaledContents(False)
        self.label_fail_count.setObjectName("label_fail_count")
        self.label_serial = QtWidgets.QLabel(self.widget)
        self.label_serial.setGeometry(QtCore.QRect(30, 110, 231, 20))
        self.label_serial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serial.setObjectName("label_serial")
        self.label_serial_2 = QtWidgets.QLabel(self.widget)
        self.label_serial_2.setGeometry(QtCore.QRect(826, 290, 188, 112))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_serial_2.setFont(font)
        self.label_serial_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_serial_2.setScaledContents(False)
        self.label_serial_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serial_2.setObjectName("label_serial_2")
        self.label_ferite = QtWidgets.QLabel(self.widget)
        self.label_ferite.setGeometry(QtCore.QRect(580, 290, 241, 112))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_ferite.setFont(font)
        self.label_ferite.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ferite.setScaledContents(False)
        self.label_ferite.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ferite.setObjectName("label_ferite")
        self.label_wireconn_status = QtWidgets.QLabel(self.widget)
        self.label_wireconn_status.setGeometry(QtCore.QRect(920, 70, 95, 102))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_wireconn_status.setFont(font)
        self.label_wireconn_status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_wireconn_status.setScaledContents(False)
        self.label_wireconn_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wireconn_status.setObjectName("label_wireconn_status")
        self.label_count = QtWidgets.QLabel(self.widget)
        self.label_count.setGeometry(QtCore.QRect(70, 415, 59, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_count.setFont(font)
        self.label_count.setObjectName("label_count")
        self.label_pass_count = QtWidgets.QLabel(self.widget)
        self.label_pass_count.setGeometry(QtCore.QRect(270, 415, 59, 16))
        self.label_pass_count.setObjectName("label_pass_count")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(306, 180, 269, 102))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setGeometry(QtCore.QRect(580, 71, 335, 102))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setText("")
        self.label_19.setScaledContents(False)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setGeometry(QtCore.QRect(750, 180, 166, 102))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setText("")
        self.label_20.setScaledContents(False)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(670, 75, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(306, 71, 269, 102))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(7, 10, 291, 391))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setText("")
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(306, 10, 269, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_yeild_count = QtWidgets.QLabel(self.widget)
        self.label_yeild_count.setGeometry(QtCore.QRect(710, 415, 59, 16))
        self.label_yeild_count.setObjectName("label_yeild_count")
        self.setting_button = QtWidgets.QPushButton(self.widget)
        self.setting_button.setGeometry(QtCore.QRect(10, 320, 281, 81))
        self.setting_button.setObjectName("setting_button")
        self.label_volt = QtWidgets.QLabel(self.widget)
        self.label_volt.setGeometry(QtCore.QRect(587, 112, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_volt.setFont(font)
        self.label_volt.setAutoFillBackground(False)
        self.label_volt.setStyleSheet("background:rgb(0, 0, 0);\n"
"color:rgb(157, 255, 0);\n"
"border: 1px solid black;\n"
"")
        self.label_volt.setFrameShape(QtWidgets.QFrame.Box)
        self.label_volt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_volt.setText("")
        self.label_volt.setScaledContents(False)
        self.label_volt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volt.setObjectName("label_volt")
        self.label_res_1 = QtWidgets.QLabel(self.widget)
        self.label_res_1.setGeometry(QtCore.QRect(587, 205, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_res_1.setFont(font)
        self.label_res_1.setAutoFillBackground(False)
        self.label_res_1.setStyleSheet("background:rgb(0, 0, 0);\n"
"color:rgb(157, 255, 0);\n"
"border: 1px solid black;\n"
"")
        self.label_res_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_res_1.setText("")
        self.label_res_1.setScaledContents(False)
        self.label_res_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_res_1.setObjectName("label_res_1")
        self.label_res_2 = QtWidgets.QLabel(self.widget)
        self.label_res_2.setGeometry(QtCore.QRect(757, 205, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_res_2.setFont(font)
        self.label_res_2.setAutoFillBackground(False)
        self.label_res_2.setStyleSheet("background:rgb(0, 0, 0);\n"
"color:rgb(157, 255, 0);\n"
"border: 1px solid black;\n"
"")
        self.label_res_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_res_2.setText("")
        self.label_res_2.setScaledContents(False)
        self.label_res_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_res_2.setObjectName("label_res_2")
        self.label_mode = QtWidgets.QLabel(self.widget)
        self.label_mode.setGeometry(QtCore.QRect(7, 449, 1007, 143))
        font = QtGui.QFont()
        font.setPointSize(84)
        self.label_mode.setFont(font)
        self.label_mode.setFrameShape(QtWidgets.QFrame.Box)
        self.label_mode.setScaledContents(False)
        self.label_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mode.setObjectName("label_mode")
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_16.raise_()
        self.label_11.raise_()
        self.label_contact_status.raise_()
        self.label_18.raise_()
        self.label_5.raise_()
        self.label_12.raise_()
        self.label_date.raise_()
        self.label_conn_key.raise_()
        self.label_function.raise_()
        self.label_part.raise_()
        self.label_time.raise_()
        self.label_fail_count.raise_()
        self.label_serial.raise_()
        self.label_serial_2.raise_()
        self.label_ferite.raise_()
        self.label_wireconn_status.raise_()
        self.label_count.raise_()
        self.label_pass_count.raise_()
        self.label_8.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_10.raise_()
        self.label_yeild_count.raise_()
        self.setting_button.raise_()
        self.label_volt.raise_()
        self.label_res_1.raise_()
        self.label_res_2.raise_()
        self.label_mode.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "Value"))
        self.label_contact_status.setText(_translate("Form", "Value"))
        self.label_5.setText(_translate("Form", "Clear"))
        self.label_12.setText(_translate("Form", "Value"))
        self.label_date.setText(_translate("Form", "DATE No: "))
        self.label_conn_key.setText(_translate("Form", "Connector key"))
        self.label_function.setText(_translate("Form", "Function: "))
        self.label_part.setText(_translate("Form", "PART No: "))
        self.label_time.setText(_translate("Form", "TIME No: "))
        self.label_fail_count.setText(_translate("Form", "Fail: 0"))
        self.label_serial.setText(_translate("Form", "SERIAL No: "))
        self.label_serial_2.setText(_translate("Form", "Serial"))
        self.label_ferite.setText(_translate("Form", "Ferite"))
        self.label_wireconn_status.setText(_translate("Form", "Value"))
        self.label_count.setText(_translate("Form", "Count: 0"))
        self.label_pass_count.setText(_translate("Form", "Pass: 0"))
        self.label_8.setText(_translate("Form", "Contact resistance"))
        self.label_6.setText(_translate("Form", "Volt"))
        self.label_7.setText(_translate("Form", "Wire connection test"))
        self.label_10.setText(_translate("Form", "Test"))
        self.label_yeild_count.setText(_translate("Form", "Yeild: 0"))
        self.setting_button.setText(_translate("Form", "Sittings"))
        self.label_mode.setText(_translate("Form", "Manual"))


