# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/setting.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.widget.setObjectName("widget")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(0, 50, 1024, 8))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.button_close = QtWidgets.QPushButton(self.widget)
        self.button_close.setGeometry(QtCore.QRect(0, 520, 1021, 50))
        self.button_close.setObjectName("button_close")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(50, 270, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setGeometry(QtCore.QRect(0, 410, 1024, 8))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(50, 150, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(200, 330, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(200, 370, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setGeometry(QtCore.QRect(0, 350, 1024, 8))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.button_set = QtWidgets.QPushButton(self.widget)
        self.button_set.setGeometry(QtCore.QRect(0, 420, 1021, 50))
        self.button_set.setObjectName("button_set")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(450, 10, 111, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.check_box_report = QtWidgets.QCheckBox(self.widget)
        self.check_box_report.setGeometry(QtCore.QRect(630, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.check_box_report.setFont(font)
        self.check_box_report.setText("")
        self.check_box_report.setIconSize(QtCore.QSize(16, 16))
        self.check_box_report.setChecked(False)
        self.check_box_report.setObjectName("check_box_report")
        self.label_ip = QtWidgets.QLabel(self.widget)
        self.label_ip.setGeometry(QtCore.QRect(650, 370, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_ip.setFont(font)
        self.label_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ip.setObjectName("label_ip")
        self.spin_box_count_set = QtWidgets.QSpinBox(self.widget)
        self.spin_box_count_set.setGeometry(QtCore.QRect(691, 310, 61, 31))
        self.spin_box_count_set.setObjectName("spin_box_count_set")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(50, 240, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.check_box_print_label = QtWidgets.QCheckBox(self.widget)
        self.check_box_print_label.setGeometry(QtCore.QRect(630, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.check_box_print_label.setFont(font)
        self.check_box_print_label.setText("")
        self.check_box_print_label.setIconSize(QtCore.QSize(16, 16))
        self.check_box_print_label.setChecked(False)
        self.check_box_print_label.setObjectName("check_box_print_label")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(200, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(0, 230, 1024, 8))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(0, 110, 1024, 8))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(50, 180, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(0, 290, 1024, 8))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.button_exit = QtWidgets.QPushButton(self.widget)
        self.button_exit.setGeometry(QtCore.QRect(0, 470, 1021, 50))
        self.button_exit.setObjectName("button_exit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.check_box_yeild = QtWidgets.QCheckBox(self.widget)
        self.check_box_yeild.setGeometry(QtCore.QRect(630, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.check_box_yeild.setFont(font)
        self.check_box_yeild.setText("")
        self.check_box_yeild.setIconSize(QtCore.QSize(16, 16))
        self.check_box_yeild.setChecked(False)
        self.check_box_yeild.setObjectName("check_box_yeild")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.button_config = QtWidgets.QPushButton(self.widget)
        self.button_config.setGeometry(QtCore.QRect(250, 60, 771, 51))
        self.button_config.setObjectName("button_config")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(50, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(0, 170, 1024, 8))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 210, 161, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_close.setText(_translate("Form", "Close test program"))
        self.label_9.setText(_translate("Form", "On/Off Report"))
        self.label_5.setText(_translate("Form", "Show/hide yeild"))
        self.label_11.setText(_translate("Form", "Count set"))
        self.label_12.setText(_translate("Form", "IP Address"))
        self.button_set.setText(_translate("Form", "Set machine and operator"))
        self.label.setText(_translate("Form", "Settings"))
        self.label_ip.setText(_translate("Form", "IP Address"))
        self.label_8.setText(_translate("Form", "Report"))
        self.label_10.setText(_translate("Form", "Count"))
        self.label_6.setText(_translate("Form", "Print label"))
        self.button_exit.setText(_translate("Form", "Exit"))
        self.label_2.setText(_translate("Form", "Model setting"))
        self.label_3.setText(_translate("Form", "Set model configuration"))
        self.button_config.setText(_translate("Form", "Config"))
        self.label_4.setText(_translate("Form", "Show yeild"))
        self.label_7.setText(_translate("Form", "On/Off Print label"))


